### PR TITLE
onyx: introduce dtbToolONYX

### PR DESCRIPTION
**Pull request by kimmoli**

### CODE REVIEW

**Comment by taaem** [comment]
is there any difference to this commit https://github.com/MasterAwesome/android_device_oneplus_onyx/commit/42e6e38595ad7392e35cedf8422074effb0e1a5a?

**Comment by kimmoli** [comment]
They should be same, If you mean why not pull original commit, iirc it was lost when doing git things (rebasing this on top of current state). I can redo this properly...

**Comment by taaem** [comment]
No it should be alright I was just wondering if there was a reason for this.

**Comment by taaem** [comment]
lgtm

**Pull request merged**
